// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using HdrHistogram.Iteration;

namespace HdrHistogram.Output
{
    internal interface IOutputFormatter
    {
        void WriteHeader();
        void WriteValue(HistogramIterationValue value);
        void WriteFooter(HistogramBase histogram);
    }
}