// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using HdrHistogram.Utilities;

namespace HdrHistogram.Persistence
{
    sealed class IntCountsDecoder : SimpleCountsDecoder
    {
        public override int WordSize => 4;

        protected override long ReadValue(ByteBuffer sourceBuffer)
        {
            return sourceBuffer.GetInt();
        }
    }
}