// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using HdrHistogram.Utilities;

namespace HdrHistogram.Persistence
{
    sealed class LongCountsDecoder : SimpleCountsDecoder
    {
        public override int WordSize => 8;
        protected override long ReadValue(ByteBuffer sourceBuffer)
        {
            return sourceBuffer.GetLong();
        }
    }
}