// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using HdrHistogram.Utilities;

namespace HdrHistogram.Persistence
{
    sealed class ShortCountsDecoder : SimpleCountsDecoder
    {
        public override int WordSize => 2;
        protected override long ReadValue(ByteBuffer sourceBuffer)
        {
            return sourceBuffer.GetShort();
        }
    }
}